language: python
sudo: false

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

env:
  - PYTHONPATH=~/vtk-precise64/lib/python2.7/site-packages:~/vtk-precise64/lib LD_LIBRARY_PATH=~/vtk-precise64/lib:~/local/lib:~/local/lib/R/lib

before_install:
  # download VTK
  - wget http://midas3.kitware.com/midas/download/bitstream/366970/vtk-precise64-118242.tar.gz -O vtk-precise64.tar.gz
  - tar xzvf vtk-precise64.tar.gz -C ~
  # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install: # Install packages
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  # Coverage packages are on my binstar channel
  - "pip install python-coveralls coverage"
  - "pip install -r requirements.txt"

script: # Run test
  - python -c "import vtk"
  - nosetests --with-coverage --with-doctest roygbiv

after_success: # Calculate coverage
  - coveralls --config_file .coveragerc
